version: '3'

services:
  ocr-app:
    build: .
    ports:
      - "8011:8011"
      - "8012:8012"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - DOCKER_ENV=true
      - SECRET_KEY=YourSecretKeyHere
    restart: unless-stopped
